### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by makroxyz** [librenms/laravel-vue-i18n-generator#5]
Please release a L9 version, just need to modify composer.json

**Comment by dvdheiden** [comment]
There's already a PR opened: https://github.com/librenms/laravel-vue-i18n-generator/pull/4. We should wait for that one to be merged and released.

**Comment by paulocastellano** [comment]
Any reason for not was merged yet? @Jellyfrog

**Comment by paulocastellano** [comment]
@Jellyfrog that's not released?

**Comment by Jellyfrog** [comment]
Fixed

**Comment by paulocastellano** [comment]
@Jellyfrog thank you!
